/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as GiftingRouteImport } from './routes/gifting'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections_.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCollectionsSlugRouteImport } from './routes/admin.collections.$slug'

const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftingRoute = GiftingRouteImport.update({
  id: '/gifting',
  path: '/gifting',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections_/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollectionsSlugRoute = AdminCollectionsSlugRouteImport.update({
  id: '/admin/collections/$slug',
  path: '/admin/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/gifting': typeof GiftingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/collections/$slug': typeof AdminCollectionsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/gifting': typeof GiftingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/collections/$slug': typeof AdminCollectionsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/gifting': typeof GiftingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/collections_/$slug': typeof CollectionsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/collections/$slug': typeof AdminCollectionsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/collections'
    | '/contact'
    | '/gifting'
    | '/sitemap.xml'
    | '/story'
    | '/admin/login'
    | '/collections/$slug'
    | '/admin/'
    | '/admin/collections/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/collections'
    | '/contact'
    | '/gifting'
    | '/sitemap.xml'
    | '/story'
    | '/admin/login'
    | '/collections/$slug'
    | '/admin'
    | '/admin/collections/$slug'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/collections'
    | '/contact'
    | '/gifting'
    | '/sitemap.xml'
    | '/story'
    | '/admin/login'
    | '/collections_/$slug'
    | '/admin/'
    | '/admin/collections/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CollectionsRoute: typeof CollectionsRoute
  ContactRoute: typeof ContactRoute
  GiftingRoute: typeof GiftingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoryRoute: typeof StoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCollectionsSlugRoute: typeof AdminCollectionsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifting': {
      id: '/gifting'
      path: '/gifting'
      fullPath: '/gifting'
      preLoaderRoute: typeof GiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections_/$slug': {
      id: '/collections_/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collections/$slug': {
      id: '/admin/collections/$slug'
      path: '/admin/collections/$slug'
      fullPath: '/admin/collections/$slug'
      preLoaderRoute: typeof AdminCollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CollectionsRoute: CollectionsRoute,
  ContactRoute: ContactRoute,
  GiftingRoute: GiftingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoryRoute: StoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCollectionsSlugRoute: AdminCollectionsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
